---
- name: Install apps
  become: true
  hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  roles:
    - core-setup
    - git-setup
    - zsh
    - ssh
    - dotfiles
    - brave
    - node-setup
    - npm-packages
    - nvim-setup
    - productivity-tools
