---
- name: Install apps
  become: true
  hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home_directory: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
  - name: Update apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  roles:
    - brave
    - discord
    - productivity-tools
