- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "hugo.castell@outlook.fr"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Hugo-CASTELL"
  tags:
  - git-personal
