---
- name: Installing stow
  apt: 
    name: [ "stow" ]

- name: Remove dotfiles
  shell: rm -rf {{ home_directory }}/.dotfiles

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:Hugo-CASTELL/.dotfiles.git'
    dest: "{{ home_directory }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Ensure execute permissions for script 1 (stow_files)
  ansible.builtin.file:
    path: "{{ home_directory }}/.dotfiles/stow_files"
    mode: "0777"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: Ensure execute permissions for script 2 (install)
  ansible.builtin.file:
    path: "{{ home_directory }}/.dotfiles/install"
    mode: "0777"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: Stow dotfiles
  shell: "zsh {{ home_directory }}/.dotfiles/stow_files"
  become_user: "{{ user }}"

