---
- name: Install ZSH
  apt: name=zsh
    
- name: Change shell to zsh
  shell: chsh -s $(which zsh)

- name: Remove .oh-my-zsh
  shell: rm -rf ~/.oh-my-zsh
  become_user: "{{ user }}"

- name: Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  become_user: "{{ user }}"

- name: Install zsh-autosuggestions
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
