---
- name: Check if keyring exists (Spotify)
  ansible.builtin.stat:
    path: /etc/apt/trusted.gpg.d/spotify.gpg
  register: keyring_file

- name: Add Spotify Gpg Keys
  shell: curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
  become: true
  when: not keyring_file.stat.exists

- name: Add repository to list
  shell: echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
  when: not keyring_file.stat.exists
  become: true

- name: Install spotify
  apt: 
    name: spotify-client
    update_cache: yes
    state: latest
  become: true
