- name: Remove neovim
  become: true
  shell: rm -rf ~/neovim
  become_user: "{{ user }}"

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ home_directory }}/neovim"

- name: Build neovim
  shell: "cd {{ home_directory }}/neovim && make -j 20"

- name: Install neovim
  become: true
  shell: "cd {{ home_directory }}/neovim && make install"

- name: Install a debugger to call for neovim
  apt:
    name: ["lldb"]
